# Generated by Django 3.2.6 on 2022-04-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('picrure', models.FileField(default='user picture/prof.png', upload_to='user picture/', verbose_name='picture')),
                ('first_name', models.CharField(max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(max_length=60, verbose_name='Last name')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('phone_number', models.BigIntegerField(default=0, verbose_name='Phone Number')),
                ('State', models.CharField(blank=True, max_length=100, verbose_name='State')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=400, verbose_name='Address')),
                ('National_Code', models.BigIntegerField(default=0, verbose_name='National Code')),
                ('Student_Number', models.BigIntegerField(default=0, verbose_name='Student Number')),
                ('Responsibility', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('Score', models.IntegerField(default=0, verbose_name='Score')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
