# Generated by Django 3.2.13 on 2022-06-21 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_responsibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'کاربران ', 'verbose_name_plural': 'کاربران'},
        ),
    ]
