# Generated by Django 3.2.6 on 2022-06-07 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام فصل')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='نام دوره')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('cost', models.IntegerField(default=0, verbose_name='قیمت')),
                ('isfinish', models.BooleanField(default=False, verbose_name='آیا دوره تمام شده است؟')),
                ('language', models.CharField(default='فارسی', max_length=100, verbose_name='زبان')),
                ('duration', models.IntegerField(null=True, verbose_name='مدت زمان دوره')),
                ('level', models.CharField(max_length=100, null=True, verbose_name='سطح')),
                ('number_of_seasons', models.IntegerField(default=1, verbose_name='تعداد فصل ها')),
                ('teacher', models.CharField(max_length=60, null=True, verbose_name='مدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='User_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='دوره')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='answer')),
                ('wrong_answer', models.CharField(max_length=100, verbose_name='wrong')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.FileField(upload_to='course_movie/', verbose_name='movie')),
                ('note', models.TextField(verbose_name='توضیحات')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapter', verbose_name='فصل')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='درس'),
        ),
    ]
