# Generated by Django 3.2.6 on 2022-06-05 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='مدت زمان دوره'),
        ),
        migrations.AddField(
            model_name='courses',
            name='isfinish',
            field=models.BooleanField(default=False, verbose_name='آیا دوره تمام شده است؟'),
        ),
        migrations.AddField(
            model_name='courses',
            name='language',
            field=models.CharField(default='فارسی', max_length=100, verbose_name='زبان'),
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.CharField(max_length=100, null=True, verbose_name='سطح'),
        ),
        migrations.AddField(
            model_name='courses',
            name='number_of_seasons',
            field=models.IntegerField(default=1, verbose_name='تعداد فصل ها'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.CharField(max_length=60, null=True, verbose_name='مدرس'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=60, verbose_name='نام دوره'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='درس'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='note',
            field=models.TextField(verbose_name='توضیحات'),
        ),
    ]
