# Generated by Django 3.2.13 on 2022-06-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'نظر', 'verbose_name_plural': 'نظر'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name': 'اطلاعیه ها', 'verbose_name_plural': 'اطلاعیه ها'},
        ),
    ]
