# Generated by Django 3.2.6 on 2022-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
        migrations.AlterField(
            model_name='account',
            name='National_Code',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='National Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='Responsibility',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='State',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='account',
            name='Student_Number',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Student Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='first_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='picrure',
            field=models.FileField(blank=True, default='user picture/prof.png', upload_to='user picture/', verbose_name='picture'),
        ),
    ]
