version: "3.9"

services:
  db-user-service:
    container_name: db-user-service
    image: postgres
    volumes:
      - ./data/db-user-service:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
  user-service:
    container_name: user-service
    build: ./users/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./users/:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=users
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
    depends_on:
      - db-user-service

############################ plan service ##########################
  db-plan-service:
    container_name: db-plan-service
    image: postgres
    volumes:
      - ./data/db-plan-service:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=plan
      - POSTGRES_USER=plan
      - POSTGRES_PASSWORD=plan
  plan-service:
    container_name: plan-service
    build: ./plan/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./plan/:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=plan
      - POSTGRES_USER=plan
      - POSTGRES_PASSWORD=plan
    depends_on:
      - db-plan-service

########################################### course service #################################

  db-course-service:
    container_name: db-course-service
    image: postgres
    volumes:
      - ./data/db-course-service:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=course
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=course

  course-service:
    container_name: course-service
    build: ./course/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./course/:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=course
      - POSTGRES_USER=course
      - POSTGRES_PASSWORD=course
    depends_on:
      - db-course-service
