# Generated by Django 3.2.6 on 2022-06-21 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Hashtak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'هشتک ها',
                'verbose_name_plural': 'هشتک ها',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('cost', models.IntegerField(verbose_name='Cost')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('duration', models.DateTimeField(verbose_name='Duratios')),
                ('createor', models.IntegerField(verbose_name='createor')),
                ('is_finish', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'برنامه ها',
                'verbose_name_plural': 'برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='User_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='user')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
            options={
                'verbose_name': 'لیست ثبت نامی در برنامه',
                'verbose_name_plural': 'لیست ثبت نامی در برنامه',
            },
        ),
        migrations.CreateModel(
            name='Plan_Hashtak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.hashtak')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
            options={
                'verbose_name': 'ثبت هشتک برای برنامه ها',
                'verbose_name_plural': 'ثبت هشتک برای برنامه ها',
            },
        ),
        migrations.CreateModel(
            name='Plan_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.category')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan')),
            ],
            options={
                'verbose_name': 'دسته بندی برنامه ها',
                'verbose_name_plural': 'دسته بندی برنامه ها',
            },
        ),
    ]
